name: Eleventy Build
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@master

      - name: Build
        uses: TartanLlama/actions-eleventy@vmaster
        with:
          install_dependencies: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
