name: Eleventy Build
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Eleventy Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22']

    permissions:
      contents: write

    steps:
      - name: Git Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
